column_width = 80  # Максимальная длина строки
line_endings = "Unix"  # Использование LF или CRLF для окончания строк
indent_type = "Spaces"  # Использовать пробелы или табуляции
indent_width = 2  # Количество пробелов для отступа
